import Head from 'next/head'
import NavBar from "../components/NavBar"
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { signIn, signOut, useSession } from "next-auth/react";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>GFG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />


      <Link href="/api/auth/auth0">
        <a onClick={e => {
          e.preventDefault();
          signIn('auth0');
        }} className="rounded px-5 py-1 text-sm border-b-4 border-l-2 shadow-lg bg-black border-gray-900 text-white">
          Login
        </a>
      </Link>


    </div>
  )
}
